---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: demo-sept18
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-sept18 
  name: demo-sept18
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi